### ISSUE TITLE
KeyError: 'error' when google_api_client receives 500

### ISSUE THREAD

**Issue by david-guzman** [UCL/isenseflu-api-flask#12]
`resp` variable in HttpError does not contain `error`:
```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/opt/isenseflu/flask/venv/lib64/python3.6/site-packages/apscheduler/executors/base.py", line 125, in run_job
retval = job.func(*job.args, **job.kwargs)
File "/opt/isenseflu/flask/scheduler/score_calculator.py", line 68, in runsched
run(model_id, start, end)
File "/opt/isenseflu/flask/scheduler/score_calculator.py", line 33, in run
batch_scores = api_client.fetch_google_scores(terms, start_date, end_date)
File "/opt/isenseflu/flask/scheduler/google_api_client.py", line 93, in fetch_google_scores
code = http_error.resp['error']['code']
KeyError: 'error'
```

**Comment by david-guzman** [comment]
Issue still happening in commit 1a3af52
